
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __User = LightSwitchApplication.User

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Public NotInheritable Partial Class User
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __User, __User.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the User entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __User))
            MyBase.New(entitySet)
            
            __User.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub User_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub User_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Username As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Username)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Username, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Password As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Password)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Password, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __User, _
                __User.DetailsClass, _
                __User.DetailsClass.IImplementation, _
                __User.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __User, __User.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __User, __User.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __User.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __UserEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __User, __User.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __User, __User.DetailsClass).Entry( _
                    AddressOf __User.DetailsClass.__User_CreateNew, _
                    AddressOf __User.DetailsClass.__User_Created, _
                    AddressOf __User.DetailsClass.__User_AllowSaveWithErrors)
            Private Shared Function __User_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __User)) As __User
                Return New __User(es)
            End Function
            Private Shared Sub __User_Created(e As __User)
                e.User_Created()
            End Sub
            Private Shared Function __User_AllowSaveWithErrors(e As __User) As Boolean
                Dim result As Boolean = False
                e.User_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __User, __User.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __User, __User.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __User.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __User, __User.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Username),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Password),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property Username As String
                Shadows Property Password As String
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __User.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __User.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __User)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Username", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_OnValueChanged)
                Private Shared Sub _Username_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Username, sf)
                End Sub
                Private Shared Function _Username_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Username_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Username_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Username_Validate(r)
                End Sub
                Private Shared Function _Username_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Username
                End Function
                Private Shared Sub _Username_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Username = v
                End Sub
                Private Shared Sub _Username_OnValueChanged(e As __User)
                    e.Username_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Password", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_OnValueChanged)
                Private Shared Sub _Password_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Password, sf)
                End Sub
                Private Shared Function _Password_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Password_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Password_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Password_Validate(r)
                End Sub
                Private Shared Function _Password_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Password
                End Function
                Private Shared Sub _Password_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Password = v
                End Sub
                Private Shared Sub _Password_OnValueChanged(e As __User)
                    e.Password_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
