
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Customer = LightSwitchApplication.Customer

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Public NotInheritable Partial Class Customer
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Customer, __Customer.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Customer entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Customer))
            MyBase.New(entitySet)
            
            __Customer.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Customer_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Customer_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __Customer.DetailsClass.GetValue(Me, __Customer.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __Customer.DetailsClass.SetValue(Me, __Customer.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Surname As String
            Get
                Return __Customer.DetailsClass.GetValue(Me, __Customer.DetailsClass.PropertySetProperties.Surname)
            End Get
            Set
                __Customer.DetailsClass.SetValue(Me, __Customer.DetailsClass.PropertySetProperties.Surname, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Firstname As String
            Get
                Return __Customer.DetailsClass.GetValue(Me, __Customer.DetailsClass.PropertySetProperties.Firstname)
            End Get
            Set
                __Customer.DetailsClass.SetValue(Me, __Customer.DetailsClass.PropertySetProperties.Firstname, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Order)
            Get
                Return __Customer.DetailsClass.GetValue(Me, __Customer.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property OrdersQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Order)
            Get
                Return __Customer.DetailsClass.GetQuery(Me, __Customer.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Customer, _
                __Customer.DetailsClass, _
                __Customer.DetailsClass.IImplementation, _
                __Customer.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Customer, __Customer.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Customer, __Customer.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Customer.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CustomerEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Customer, __Customer.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Customer, __Customer.DetailsClass).Entry( _
                    AddressOf __Customer.DetailsClass.__Customer_CreateNew, _
                    AddressOf __Customer.DetailsClass.__Customer_Created, _
                    AddressOf __Customer.DetailsClass.__Customer_AllowSaveWithErrors)
            Private Shared Function __Customer_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Customer)) As __Customer
                Return New __Customer(es)
            End Function
            Private Shared Sub __Customer_Created(e As __Customer)
                e.Customer_Created()
            End Sub
            Private Shared Function __Customer_AllowSaveWithErrors(e As __Customer) As Boolean
                Dim result As Boolean = False
                e.Customer_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Customer, __Customer.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Customer, __Customer.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Customer.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Customer, __Customer.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Customer.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Customer.DetailsClass.PropertySetProperties.Surname),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Customer.DetailsClass.PropertySetProperties.Firstname),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Customer.DetailsClass.PropertySetProperties.Orders),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property Surname As String
                Shadows Property Firstname As String
                Shadows ReadOnly Property Orders As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Customer.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer).Data), d As __Customer.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __Customer) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __Customer, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __Customer.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __Customer.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __Customer)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Entry( _
                        "Surname", _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_Stub, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_ComputeIsReadOnly, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_Validate, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_GetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_SetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Surname_OnValueChanged)
                Private Shared Sub _Surname_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Customer.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Data), d As __Customer.DetailsClass, sf As Object)
                    c(d, d._Surname, sf)
                End Sub
                Private Shared Function _Surname_ComputeIsReadOnly(e As __Customer) As Boolean
                    Dim result As Boolean = False
                    e.Surname_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Surname_Validate(e As __Customer, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Surname_Validate(r)
                End Sub
                Private Shared Function _Surname_GetImplementationValue(d As __Customer.DetailsClass) As String
                    Return d.ImplementationEntity.Surname
                End Function
                Private Shared Sub _Surname_SetImplementationValue(d As __Customer.DetailsClass, v As String)
                    d.ImplementationEntity.Surname = v
                End Sub
                Private Shared Sub _Surname_OnValueChanged(e As __Customer)
                    e.Surname_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Entry( _
                        "Firstname", _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_Stub, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_ComputeIsReadOnly, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_Validate, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_GetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_SetImplementationValue, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Firstname_OnValueChanged)
                Private Shared Sub _Firstname_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Customer.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Data), d As __Customer.DetailsClass, sf As Object)
                    c(d, d._Firstname, sf)
                End Sub
                Private Shared Function _Firstname_ComputeIsReadOnly(e As __Customer) As Boolean
                    Dim result As Boolean = False
                    e.Firstname_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Firstname_Validate(e As __Customer, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Firstname_Validate(r)
                End Sub
                Private Shared Function _Firstname_GetImplementationValue(d As __Customer.DetailsClass) As String
                    Return d.ImplementationEntity.Firstname
                End Function
                Private Shared Sub _Firstname_SetImplementationValue(d As __Customer.DetailsClass, v As String)
                    d.ImplementationEntity.Firstname = v
                End Sub
                Private Shared Sub _Firstname_OnValueChanged(e As __Customer)
                    e.Firstname_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order).Entry( _
                        "Orders", _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Orders_Stub, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Orders_GetReferencedEntities, _
                        AddressOf __Customer.DetailsClass.PropertySetProperties._Orders_GetEntityCollection)
                Private Shared Sub _Orders_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Customer.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order).Data), d As __Customer.DetailsClass, sf As Object)
                    c(d, d._Orders, sf)
                End Sub
                Private Shared Function _Orders_GetReferencedEntities(d As __Customer.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Order)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Order, Global.LightSwitchApplication.Order.DetailsClass)(__Customer.DetailsClass.PropertySetProperties.Orders, d._Orders)
                End Function
                Private Shared Function _Orders_GetEntityCollection(d As __Customer.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Orders
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Customer, __Customer.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Customer, __Customer.DetailsClass, Global.LightSwitchApplication.Order).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
