
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("19ac3692-1970-4c16-99c0-842b6923ccc0")> 
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ApplicationData", "Gender_Person", "Gender", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ApplicationData.Implementation.Gender), "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ApplicationData.Implementation.Person), True)> 

#End Region
Namespace ApplicationData.Implementation

#Region "Contexts"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Partial Public Class ApplicationDataObjectContext
        Inherits ObjectContext

#Region "Constructors"

        ''' <summary>
        ''' Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new ApplicationDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new ApplicationDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub

#End Region

#Region "Partial Methods"

        Partial Private Sub OnContextCreated()
        End Sub

#End Region

#Region "ObjectSet Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property People() As ObjectSet(Of Person)
            Get
                If (_People Is Nothing) Then
                    _People = MyBase.CreateObjectSet(Of Person)("People")
                End If
                Return _People
            End Get
        End Property

        Private _People As ObjectSet(Of Person)

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Genders() As ObjectSet(Of Gender)
            Get
                If (_Genders Is Nothing) Then
                    _Genders = MyBase.CreateObjectSet(Of Gender)("Genders")
                End If
                Return _Genders
            End Get
        End Property

        Private _Genders As ObjectSet(Of Gender)

#End Region
#Region "AddTo Methods"

        ''' <summary>
        ''' Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToPeople(ByVal person As Person)
            MyBase.AddObject("People", person)
        End Sub

        ''' <summary>
        ''' Deprecated Method for adding a new object to the Genders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToGenders(ByVal gender As Gender)
            MyBase.AddObject("Genders", gender)
        End Sub

#End Region
    End Class

#End Region
#Region "Entities"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Gender")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Partial Public Class Gender
        Inherits EntityObject
#Region "Factory Method"

        ''' <summary>
        ''' Create a new Gender object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="genderName">Initial value of the GenderName property.</param>
        Public Shared Function CreateGender(id As Global.System.Int32, genderName As Global.System.String) As Gender
            Dim gender As Gender = New Gender
            gender.Id = id
            gender.GenderName = genderName
            Return gender
        End Function

#End Region
#Region "Primitive Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set(value As Global.System.Int32)
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property

        Private _Id As Global.System.Int32
        Partial Private Sub OnIdChanging(value As Global.System.Int32)
        End Sub

        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <DataMemberAttribute()>
        Public Property GenderName() As Global.System.String
            Get
                Return _GenderName
            End Get
            Set(value As Global.System.String)
                OnGenderNameChanging(value)
                ReportPropertyChanging("GenderName")
                _GenderName = value
                ReportPropertyChanged("GenderName")
                OnGenderNameChanged()
            End Set
        End Property

        Private _GenderName As Global.System.String
        Partial Private Sub OnGenderNameChanging(value As Global.System.String)
        End Sub

        Partial Private Sub OnGenderNameChanged()
        End Sub

#End Region
#Region "Navigation Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Gender_Person", "Person")>
        Public Property Person() As EntityCollection(Of Person)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Person)("ApplicationData.Gender_Person", "Person")
            End Get
            Set(value As EntityCollection(Of Person))
                If (Not value Is Nothing) Then
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Person)("ApplicationData.Gender_Person", "Person", value)
                End If
            End Set
        End Property

#End Region
    End Class

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Person")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Partial Public Class Person
        Inherits EntityObject
#Region "Factory Method"

        ''' <summary>
        ''' Create a new Person object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        ''' <param name="gender_Person">Initial value of the Gender_Person property.</param>
        Public Shared Function CreatePerson(id As Global.System.Int32, name As Global.System.String, gender_Person As Global.System.Int32) As Person
            Dim person As Person = New Person
            person.Id = id
            person.Name = name
            person.Gender_Person = gender_Person
            Return person
        End Function

#End Region
#Region "Primitive Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set(value As Global.System.Int32)
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property

        Private _Id As Global.System.Int32
        Partial Private Sub OnIdChanging(value As Global.System.Int32)
        End Sub

        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set(value As Global.System.String)
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = value
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property

        Private _Name As Global.System.String
        Partial Private Sub OnNameChanging(value As Global.System.String)
        End Sub

        Partial Private Sub OnNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <DataMemberAttribute()>
        Public Property Gender_Person() As Global.System.Int32
            Get
                Return _Gender_Person
            End Get
            Set(value As Global.System.Int32)
                OnGender_PersonChanging(value)
                ReportPropertyChanging("Gender_Person")
                _Gender_Person = value
                ReportPropertyChanged("Gender_Person")
                OnGender_PersonChanged()
            End Set
        End Property

        Private _Gender_Person As Global.System.Int32
        Partial Private Sub OnGender_PersonChanging(value As Global.System.Int32)
        End Sub

        Partial Private Sub OnGender_PersonChanged()
        End Sub

#End Region
#Region "Navigation Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Gender_Person", "Gender")>
        Public Property Gender() As Gender
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Gender)("ApplicationData.Gender_Person", "Gender").Value
            End Get
            Set(value As Gender)
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Gender)("ApplicationData.Gender_Person", "Gender").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property GenderReference() As EntityReference(Of Gender)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Gender)("ApplicationData.Gender_Person", "Gender")
            End Get
            Set(value As EntityReference(Of Gender))
                If (Not value Is Nothing) Then
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Gender)("ApplicationData.Gender_Person", "Gender", value)
                End If
            End Set
        End Property

#End Region
    End Class

#End Region

End Namespace
