'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
    Partial Public NotInheritable Class Application
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.DataWorkspace)

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(ByVal applicationDefinition As Global.Microsoft.LightSwitch.Model.IApplicationDefinition)
            MyBase.New(applicationDefinition)

            Global.LightSwitchApplication.Application.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Application_Initialize()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Application_LoggedIn()
        End Sub
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Shared Shadows ReadOnly Property Current As Global.LightSwitchApplication.Application
            Get
                Return DirectCast(Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Current, Global.LightSwitchApplication.Application)
            End Get
        End Property

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SliderControl905_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SliderControl905_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowSliderControl905 screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowSliderControl905()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowSliderControl905)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SliderControlResult905Pt2_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SliderControlResult905Pt2_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowSliderControlResult905Pt2 screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowSliderControlResult905Pt2()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowSliderControlResult905Pt2)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableHyperlinksGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableHyperlinksGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableHyperlinksGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableHyperlinksGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableHyperlinksGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PasswordBoxControl901_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PasswordBoxControl901_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowPasswordBoxControl901 screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowPasswordBoxControl901()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowPasswordBoxControl901)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableCustomersGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableCustomersGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableCustomersGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableCustomersGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableCustomersGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ComboBoxControl902_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ComboBoxControl902_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowComboBoxControl902 screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowComboBoxControl902()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowComboBoxControl902)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub HyperlinkButton904_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub HyperlinkButton904_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowHyperlinkButton904 screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowHyperlinkButton904()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowHyperlinkButton904)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RichTextControl908_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RichTextControl908_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowRichTextControl908 screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowRichTextControl908()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowRichTextControl908)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableProductsGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableProductsGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableProductsGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableProductsGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableProductsGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WebBrowserCtrlSearch910_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WebBrowserCtrlSearch910_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowWebBrowserCtrlSearch910 screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowWebBrowserCtrlSearch910()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowWebBrowserCtrlSearch910)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WebBrowserCtrlDetail910_CanRun(ByRef result As Boolean, ByVal HyperlinkId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WebBrowserCtrlDetail910_Run(ByRef handled As Boolean, ByVal HyperlinkId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowWebBrowserCtrlDetail910 screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowWebBrowserCtrlDetail910(ByVal HyperlinkId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowWebBrowserCtrlDetail910, HyperlinkId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomButton912_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomButton912_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCustomButton912 screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCustomButton912()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCustomButton912)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.Application.DetailsClass.PropertySet, Global.LightSwitchApplication.Application.DetailsClass.CommandSet, Global.LightSwitchApplication.Application.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializeCommandEntry = Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSliderControl905
                Dim initializeMethodEntry = Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSliderControl905
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ApplicationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_Initialized, _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_LoggedIn)
            Private Shared Sub __Application_Initialized(a As Global.LightSwitchApplication.Application)
                a.Application_Initialize()
            End Sub
            Private Shared Sub __Application_LoggedIn(a As Global.LightSwitchApplication.Application)
                a.Application_LoggedIn()
            End Sub

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As Global.LightSwitchApplication.Application.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As Global.LightSwitchApplication.Application.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As Global.LightSwitchApplication.Application.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Protected Overrides Function CreateScreen(ByVal screenName As String, ByVal ParamArray args() As Object) As Global.Microsoft.LightSwitch.Client.IScreenObject
                Select Case screenName
                    Case "SliderControl905"
                        Return Global.LightSwitchApplication.SliderControl905.CreateInstance()
                    Case "SliderControlResult905Pt2"
                        Return Global.LightSwitchApplication.SliderControlResult905Pt2.CreateInstance()
                    Case "EditableHyperlinksGrid"
                        Return Global.LightSwitchApplication.EditableHyperlinksGrid.CreateInstance()
                    Case "PasswordBoxControl901"
                        Return Global.LightSwitchApplication.PasswordBoxControl901.CreateInstance()
                    Case "EditableCustomersGrid"
                        Return Global.LightSwitchApplication.EditableCustomersGrid.CreateInstance()
                    Case "ComboBoxControl902"
                        Return Global.LightSwitchApplication.ComboBoxControl902.CreateInstance()
                    Case "HyperlinkButton904"
                        Return Global.LightSwitchApplication.HyperlinkButton904.CreateInstance()
                    Case "RichTextControl908"
                        Return Global.LightSwitchApplication.RichTextControl908.CreateInstance()
                    Case "EditableProductsGrid"
                        Return Global.LightSwitchApplication.EditableProductsGrid.CreateInstance()
                    Case "WebBrowserCtrlSearch910"
                        Return Global.LightSwitchApplication.WebBrowserCtrlSearch910.CreateInstance()
                    Case "WebBrowserCtrlDetail910"
                        Return Global.LightSwitchApplication.WebBrowserCtrlDetail910.CreateInstance(CType(args(0), Integer))
                    Case "CustomButton912"
                        Return Global.LightSwitchApplication.CustomButton912.CreateInstance()
                End Select
            
                Return MyBase.CreateScreen(screenName, args)
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationPropertySet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationCommandSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowSliderControl905 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSliderControl905), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSliderControlResult905Pt2 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowSliderControlResult905Pt2), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableHyperlinksGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableHyperlinksGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowPasswordBoxControl901 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowPasswordBoxControl901), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableCustomersGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableCustomersGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowComboBoxControl902 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowComboBoxControl902), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowHyperlinkButton904 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowHyperlinkButton904), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowRichTextControl908 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowRichTextControl908), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableProductsGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableProductsGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowWebBrowserCtrlSearch910 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowWebBrowserCtrlSearch910), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCustomButton912 As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCustomButton912), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationMethodSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowSliderControl905 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSliderControl905), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowSliderControlResult905Pt2 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowSliderControlResult905Pt2), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableHyperlinksGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableHyperlinksGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowPasswordBoxControl901 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowPasswordBoxControl901), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableCustomersGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableCustomersGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowComboBoxControl902 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowComboBoxControl902), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowHyperlinkButton904 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowHyperlinkButton904), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowRichTextControl908 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowRichTextControl908), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableProductsGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableProductsGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowWebBrowserCtrlSearch910 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowWebBrowserCtrlSearch910), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowWebBrowserCtrlDetail910 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowWebBrowserCtrlDetail910), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCustomButton912 As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCustomButton912), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties

                Public Shared ReadOnly ShowSliderControl905 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSliderControl905",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSliderControl905_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSliderControl905_CreateExecutableObject)
                Private Shared Sub _ShowSliderControl905_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSliderControl905Command, sf)
                End Sub
                Private Shared Function _ShowSliderControl905_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowSliderControl905.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowSliderControlResult905Pt2 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSliderControlResult905Pt2",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSliderControlResult905Pt2_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowSliderControlResult905Pt2_CreateExecutableObject)
                Private Shared Sub _ShowSliderControlResult905Pt2_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSliderControlResult905Pt2Command, sf)
                End Sub
                Private Shared Function _ShowSliderControlResult905Pt2_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowSliderControlResult905Pt2.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableHyperlinksGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableHyperlinksGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableHyperlinksGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableHyperlinksGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableHyperlinksGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableHyperlinksGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableHyperlinksGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableHyperlinksGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowPasswordBoxControl901 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowPasswordBoxControl901",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowPasswordBoxControl901_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowPasswordBoxControl901_CreateExecutableObject)
                Private Shared Sub _ShowPasswordBoxControl901_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowPasswordBoxControl901Command, sf)
                End Sub
                Private Shared Function _ShowPasswordBoxControl901_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowPasswordBoxControl901.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableCustomersGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableCustomersGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableCustomersGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableCustomersGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableCustomersGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableCustomersGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableCustomersGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableCustomersGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowComboBoxControl902 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowComboBoxControl902",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowComboBoxControl902_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowComboBoxControl902_CreateExecutableObject)
                Private Shared Sub _ShowComboBoxControl902_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowComboBoxControl902Command, sf)
                End Sub
                Private Shared Function _ShowComboBoxControl902_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowComboBoxControl902.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowHyperlinkButton904 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowHyperlinkButton904",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowHyperlinkButton904_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowHyperlinkButton904_CreateExecutableObject)
                Private Shared Sub _ShowHyperlinkButton904_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowHyperlinkButton904Command, sf)
                End Sub
                Private Shared Function _ShowHyperlinkButton904_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowHyperlinkButton904.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowRichTextControl908 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowRichTextControl908",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowRichTextControl908_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowRichTextControl908_CreateExecutableObject)
                Private Shared Sub _ShowRichTextControl908_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowRichTextControl908Command, sf)
                End Sub
                Private Shared Function _ShowRichTextControl908_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowRichTextControl908.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableProductsGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableProductsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableProductsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableProductsGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableProductsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableProductsGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableProductsGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableProductsGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowWebBrowserCtrlSearch910 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowWebBrowserCtrlSearch910",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowWebBrowserCtrlSearch910_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowWebBrowserCtrlSearch910_CreateExecutableObject)
                Private Shared Sub _ShowWebBrowserCtrlSearch910_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowWebBrowserCtrlSearch910Command, sf)
                End Sub
                Private Shared Function _ShowWebBrowserCtrlSearch910_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowWebBrowserCtrlSearch910.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowCustomButton912 As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCustomButton912",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCustomButton912_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCustomButton912_CreateExecutableObject)
                Private Shared Sub _ShowCustomButton912_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCustomButton912Command, sf)
                End Sub
                Private Shared Function _ShowCustomButton912_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCustomButton912.CreateInvocation(New Object(0 - 1) { })
                End Function

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties

                Public Shared ReadOnly ShowSliderControl905 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSliderControl905",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControl905_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControl905_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControl905_InvokeMethod)
                Private Shared Sub _ShowSliderControl905_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSliderControl905Method, sf)
                End Sub
                Private Shared Function _ShowSliderControl905_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.SliderControl905_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowSliderControl905_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.SliderControl905_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:SliderControl905", Function() Global.LightSwitchApplication.SliderControl905.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowSliderControlResult905Pt2 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowSliderControlResult905Pt2",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControlResult905Pt2_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControlResult905Pt2_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowSliderControlResult905Pt2_InvokeMethod)
                Private Shared Sub _ShowSliderControlResult905Pt2_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowSliderControlResult905Pt2Method, sf)
                End Sub
                Private Shared Function _ShowSliderControlResult905Pt2_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.SliderControlResult905Pt2_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowSliderControlResult905Pt2_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.SliderControlResult905Pt2_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:SliderControlResult905Pt2", Function() Global.LightSwitchApplication.SliderControlResult905Pt2.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableHyperlinksGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableHyperlinksGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableHyperlinksGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableHyperlinksGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableHyperlinksGrid_InvokeMethod)
                Private Shared Sub _ShowEditableHyperlinksGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableHyperlinksGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableHyperlinksGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableHyperlinksGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableHyperlinksGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableHyperlinksGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EditableHyperlinksGrid", Function() Global.LightSwitchApplication.EditableHyperlinksGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowPasswordBoxControl901 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowPasswordBoxControl901",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowPasswordBoxControl901_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowPasswordBoxControl901_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowPasswordBoxControl901_InvokeMethod)
                Private Shared Sub _ShowPasswordBoxControl901_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowPasswordBoxControl901Method, sf)
                End Sub
                Private Shared Function _ShowPasswordBoxControl901_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.PasswordBoxControl901_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowPasswordBoxControl901_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.PasswordBoxControl901_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:PasswordBoxControl901", Function() Global.LightSwitchApplication.PasswordBoxControl901.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableCustomersGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableCustomersGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableCustomersGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableCustomersGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableCustomersGrid_InvokeMethod)
                Private Shared Sub _ShowEditableCustomersGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableCustomersGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableCustomersGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableCustomersGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableCustomersGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableCustomersGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EditableCustomersGrid", Function() Global.LightSwitchApplication.EditableCustomersGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowComboBoxControl902 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowComboBoxControl902",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowComboBoxControl902_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowComboBoxControl902_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowComboBoxControl902_InvokeMethod)
                Private Shared Sub _ShowComboBoxControl902_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowComboBoxControl902Method, sf)
                End Sub
                Private Shared Function _ShowComboBoxControl902_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.ComboBoxControl902_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowComboBoxControl902_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.ComboBoxControl902_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:ComboBoxControl902", Function() Global.LightSwitchApplication.ComboBoxControl902.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowHyperlinkButton904 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowHyperlinkButton904",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHyperlinkButton904_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHyperlinkButton904_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowHyperlinkButton904_InvokeMethod)
                Private Shared Sub _ShowHyperlinkButton904_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowHyperlinkButton904Method, sf)
                End Sub
                Private Shared Function _ShowHyperlinkButton904_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.HyperlinkButton904_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowHyperlinkButton904_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.HyperlinkButton904_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:HyperlinkButton904", Function() Global.LightSwitchApplication.HyperlinkButton904.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowRichTextControl908 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowRichTextControl908",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRichTextControl908_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRichTextControl908_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowRichTextControl908_InvokeMethod)
                Private Shared Sub _ShowRichTextControl908_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowRichTextControl908Method, sf)
                End Sub
                Private Shared Function _ShowRichTextControl908_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.RichTextControl908_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowRichTextControl908_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.RichTextControl908_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:RichTextControl908", Function() Global.LightSwitchApplication.RichTextControl908.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableProductsGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableProductsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableProductsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableProductsGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableProductsGrid_InvokeMethod)
                Private Shared Sub _ShowEditableProductsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableProductsGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableProductsGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableProductsGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableProductsGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableProductsGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EditableProductsGrid", Function() Global.LightSwitchApplication.EditableProductsGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowWebBrowserCtrlSearch910 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowWebBrowserCtrlSearch910",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlSearch910_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlSearch910_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlSearch910_InvokeMethod)
                Private Shared Sub _ShowWebBrowserCtrlSearch910_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowWebBrowserCtrlSearch910Method, sf)
                End Sub
                Private Shared Function _ShowWebBrowserCtrlSearch910_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.WebBrowserCtrlSearch910_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowWebBrowserCtrlSearch910_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.WebBrowserCtrlSearch910_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:WebBrowserCtrlSearch910", Function() Global.LightSwitchApplication.WebBrowserCtrlSearch910.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowWebBrowserCtrlDetail910 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowWebBrowserCtrlDetail910",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlDetail910_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlDetail910_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowWebBrowserCtrlDetail910_InvokeMethod)
                Private Shared Sub _ShowWebBrowserCtrlDetail910_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowWebBrowserCtrlDetail910Method, sf)
                End Sub
                Private Shared Function _ShowWebBrowserCtrlDetail910_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.WebBrowserCtrlDetail910_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowWebBrowserCtrlDetail910_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.WebBrowserCtrlDetail910_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:WebBrowserCtrlDetail910", Function() Global.LightSwitchApplication.WebBrowserCtrlDetail910.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCustomButton912 As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCustomButton912",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomButton912_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomButton912_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCustomButton912_InvokeMethod)
                Private Shared Sub _ShowCustomButton912_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCustomButton912Method, sf)
                End Sub
                Private Shared Function _ShowCustomButton912_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CustomButton912_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCustomButton912_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CustomButton912_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:CustomButton912", Function() Global.LightSwitchApplication.CustomButton912.CreateInstance(), args)
                    End If
                End Sub
 
            End Class

            Private _ShowSliderControl905Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSliderControlResult905Pt2Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableHyperlinksGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowPasswordBoxControl901Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableCustomersGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowComboBoxControl902Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowHyperlinkButton904Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowRichTextControl908Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableProductsGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowWebBrowserCtrlSearch910Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowWebBrowserCtrlDetail910Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCustomButton912Method As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSliderControl905Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowSliderControlResult905Pt2Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableHyperlinksGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowPasswordBoxControl901Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableCustomersGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowComboBoxControl902Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowHyperlinkButton904Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowRichTextControl908Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableProductsGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowWebBrowserCtrlSearch910Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCustomButton912Command As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

        End Class

    End Class

End Namespace
