
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("3a8be304-07b4-4895-bb18-ea174e96fddd")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ApplicationData", "Order_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ApplicationData.Implementation.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ApplicationData.Implementation.Order), True)>

#End Region
Namespace ApplicationData.Implementation
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class ApplicationDataObjectContext
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new ApplicationDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new ApplicationDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "ApplicationDataObjectContext")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property ProductFeedbacks() As ObjectSet(Of ProductFeedback)
            Get
                If (_ProductFeedbacks Is Nothing) Then
                    _ProductFeedbacks = MyBase.CreateObjectSet(Of ProductFeedback)("ProductFeedbacks")
                End If
                Return _ProductFeedbacks
            End Get
        End Property
    
        Private _ProductFeedbacks As ObjectSet(Of ProductFeedback)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Hyperlinks() As ObjectSet(Of Hyperlink)
            Get
                If (_Hyperlinks Is Nothing) Then
                    _Hyperlinks = MyBase.CreateObjectSet(Of Hyperlink)("Hyperlinks")
                End If
                Return _Hyperlinks
            End Get
        End Property
    
        Private _Hyperlinks As ObjectSet(Of Hyperlink)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Users() As ObjectSet(Of User)
            Get
                If (_Users Is Nothing) Then
                    _Users = MyBase.CreateObjectSet(Of User)("Users")
                End If
                Return _Users
            End Get
        End Property
    
        Private _Users As ObjectSet(Of User)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Customers() As ObjectSet(Of Customer)
            Get
                If (_Customers Is Nothing) Then
                    _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
                End If
                Return _Customers
            End Get
        End Property
    
        Private _Customers As ObjectSet(Of Customer)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Orders() As ObjectSet(Of Order)
            Get
                If (_Orders Is Nothing) Then
                    _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
                End If
                Return _Orders
            End Get
        End Property
    
        Private _Orders As ObjectSet(Of Order)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Products() As ObjectSet(Of Product)
            Get
                If (_Products Is Nothing) Then
                    _Products = MyBase.CreateObjectSet(Of Product)("Products")
                End If
                Return _Products
            End Get
        End Property
    
        Private _Products As ObjectSet(Of Product)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the ProductFeedbacks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToProductFeedbacks(ByVal productFeedback As ProductFeedback)
            MyBase.AddObject("ProductFeedbacks", productFeedback)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Hyperlinks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToHyperlinks(ByVal hyperlink As Hyperlink)
            MyBase.AddObject("Hyperlinks", hyperlink)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToUsers(ByVal user As User)
            MyBase.AddObject("Users", user)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCustomers(ByVal customer As Customer)
            MyBase.AddObject("Customers", customer)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrders(ByVal order As Order)
            MyBase.AddObject("Orders", order)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToProducts(ByVal product As Product)
            MyBase.AddObject("Products", product)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Customer")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Customer
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Customer object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="surname">Initial value of the Surname property.</param>
        ''' <param name="firstname">Initial value of the Firstname property.</param>
        Public Shared Function CreateCustomer(id As Global.System.Int32, surname As Global.System.String, firstname As Global.System.String) As Customer
            Dim customer as Customer = New Customer
            customer.Id = id
            customer.Surname = surname
            customer.Firstname = firstname
            Return customer
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Surname() As Global.System.String
            Get
                Return _Surname
            End Get
            Set
                OnSurnameChanging(value)
                ReportPropertyChanging("Surname")
                _Surname = value
                ReportPropertyChanged("Surname")
                OnSurnameChanged()
            End Set
        End Property
    
        Private _Surname As Global.System.String
        Private Partial Sub OnSurnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSurnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Firstname() As Global.System.String
            Get
                Return _Firstname
            End Get
            Set
                OnFirstnameChanging(value)
                ReportPropertyChanging("Firstname")
                _Firstname = value
                ReportPropertyChanged("Firstname")
                OnFirstnameChanged()
            End Set
        End Property
    
        Private _Firstname As Global.System.String
        Private Partial Sub OnFirstnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirstnameChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Order_Customer", "Order")>
         Public Property Orders() As EntityCollection(Of Order)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("ApplicationData.Order_Customer", "Order")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("ApplicationData.Order_Customer", "Order", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Hyperlink")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Hyperlink
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Hyperlink object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        ''' <param name="uRL">Initial value of the URL property.</param>
        Public Shared Function CreateHyperlink(id As Global.System.Int32, name As Global.System.String, uRL As Global.System.String) As Hyperlink
            Dim hyperlink as Hyperlink = New Hyperlink
            hyperlink.Id = id
            hyperlink.Name = name
            hyperlink.URL = uRL
            Return hyperlink
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = value
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property URL() As Global.System.String
            Get
                Return _URL
            End Get
            Set
                OnURLChanging(value)
                ReportPropertyChanging("URL")
                _URL = value
                ReportPropertyChanged("URL")
                OnURLChanged()
            End Set
        End Property
    
        Private _URL As Global.System.String
        Private Partial Sub OnURLChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnURLChanged()
        End Sub

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Order")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Order
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Order object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="orderDesc">Initial value of the OrderDesc property.</param>
        ''' <param name="orderDate">Initial value of the OrderDate property.</param>
        ''' <param name="order_Customer">Initial value of the Order_Customer property.</param>
        Public Shared Function CreateOrder(id As Global.System.Int32, orderDesc As Global.System.String, orderDate As Global.System.DateTime, order_Customer As Global.System.Int32) As Order
            Dim order as Order = New Order
            order.Id = id
            order.OrderDesc = orderDesc
            order.OrderDate = orderDate
            order.Order_Customer = order_Customer
            Return order
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderDesc() As Global.System.String
            Get
                Return _OrderDesc
            End Get
            Set
                OnOrderDescChanging(value)
                ReportPropertyChanging("OrderDesc")
                _OrderDesc = value
                ReportPropertyChanged("OrderDesc")
                OnOrderDescChanged()
            End Set
        End Property
    
        Private _OrderDesc As Global.System.String
        Private Partial Sub OnOrderDescChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOrderDescChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderDate() As Global.System.DateTime
            Get
                Return _OrderDate
            End Get
            Set
                OnOrderDateChanging(value)
                ReportPropertyChanging("OrderDate")
                _OrderDate = value
                ReportPropertyChanged("OrderDate")
                OnOrderDateChanged()
            End Set
        End Property
    
        Private _OrderDate As Global.System.DateTime
        Private Partial Sub OnOrderDateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnOrderDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Order_Customer() As Global.System.Int32
            Get
                Return _Order_Customer
            End Get
            Set
                OnOrder_CustomerChanging(value)
                ReportPropertyChanging("Order_Customer")
                _Order_Customer = value
                ReportPropertyChanged("Order_Customer")
                OnOrder_CustomerChanged()
            End Set
        End Property
    
        Private _Order_Customer As Global.System.Int32
        Private Partial Sub OnOrder_CustomerChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrder_CustomerChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Order_Customer", "Customer")>
        Public Property Customer() As Customer
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ApplicationData.Order_Customer", "Customer").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ApplicationData.Order_Customer", "Customer").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CustomerReference() As EntityReference(Of Customer)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ApplicationData.Order_Customer", "Customer")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("ApplicationData.Order_Customer", "Customer", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="Product")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Product
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Product object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="productName">Initial value of the ProductName property.</param>
        ''' <param name="productDescription">Initial value of the ProductDescription property.</param>
        Public Shared Function CreateProduct(id As Global.System.Int32, productName As Global.System.String, productDescription As Global.System.String) As Product
            Dim product as Product = New Product
            product.Id = id
            product.ProductName = productName
            product.ProductDescription = productDescription
            Return product
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductName() As Global.System.String
            Get
                Return _ProductName
            End Get
            Set
                OnProductNameChanging(value)
                ReportPropertyChanging("ProductName")
                _ProductName = value
                ReportPropertyChanged("ProductName")
                OnProductNameChanged()
            End Set
        End Property
    
        Private _ProductName As Global.System.String
        Private Partial Sub OnProductNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductDescription() As Global.System.String
            Get
                Return _ProductDescription
            End Get
            Set
                OnProductDescriptionChanging(value)
                ReportPropertyChanging("ProductDescription")
                _ProductDescription = value
                ReportPropertyChanged("ProductDescription")
                OnProductDescriptionChanged()
            End Set
        End Property
    
        Private _ProductDescription As Global.System.String
        Private Partial Sub OnProductDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductDescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property RichTextDescription() As Global.System.String
            Get
                Return _RichTextDescription
            End Get
            Set
                OnRichTextDescriptionChanging(value)
                ReportPropertyChanging("RichTextDescription")
                _RichTextDescription = value
                ReportPropertyChanged("RichTextDescription")
                OnRichTextDescriptionChanged()
            End Set
        End Property
    
        Private _RichTextDescription As Global.System.String
        Private Partial Sub OnRichTextDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRichTextDescriptionChanged()
        End Sub

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="ProductFeedback")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class ProductFeedback
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new ProductFeedback object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="productDescription">Initial value of the ProductDescription property.</param>
        ''' <param name="satisfaction">Initial value of the Satisfaction property.</param>
        Public Shared Function CreateProductFeedback(id As Global.System.Int32, productDescription As Global.System.String, satisfaction As Global.System.Int32) As ProductFeedback
            Dim productFeedback as ProductFeedback = New ProductFeedback
            productFeedback.Id = id
            productFeedback.ProductDescription = productDescription
            productFeedback.Satisfaction = satisfaction
            Return productFeedback
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductDescription() As Global.System.String
            Get
                Return _ProductDescription
            End Get
            Set
                OnProductDescriptionChanging(value)
                ReportPropertyChanging("ProductDescription")
                _ProductDescription = value
                ReportPropertyChanged("ProductDescription")
                OnProductDescriptionChanged()
            End Set
        End Property
    
        Private _ProductDescription As Global.System.String
        Private Partial Sub OnProductDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductDescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Satisfaction() As Global.System.Int32
            Get
                Return _Satisfaction
            End Get
            Set
                OnSatisfactionChanging(value)
                ReportPropertyChanging("Satisfaction")
                _Satisfaction = value
                ReportPropertyChanged("Satisfaction")
                OnSatisfactionChanged()
            End Set
        End Property
    
        Private _Satisfaction As Global.System.Int32
        Private Partial Sub OnSatisfactionChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnSatisfactionChanged()
        End Sub

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ApplicationData", Name:="User")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class User
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new User object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="username">Initial value of the Username property.</param>
        ''' <param name="password">Initial value of the Password property.</param>
        Public Shared Function CreateUser(id As Global.System.Int32, username As Global.System.String, password As Global.System.String) As User
            Dim user as User = New User
            user.Id = id
            user.Username = username
            user.Password = password
            Return user
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = value
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Username() As Global.System.String
            Get
                Return _Username
            End Get
            Set
                OnUsernameChanging(value)
                ReportPropertyChanging("Username")
                _Username = value
                ReportPropertyChanged("Username")
                OnUsernameChanged()
            End Set
        End Property
    
        Private _Username As Global.System.String
        Private Partial Sub OnUsernameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUsernameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Password() As Global.System.String
            Get
                Return _Password
            End Get
            Set
                OnPasswordChanging(value)
                ReportPropertyChanging("Password")
                _Password = value
                ReportPropertyChanged("Password")
                OnPasswordChanged()
            End Set
        End Property
    
        Private _Password As Global.System.String
        Private Partial Sub OnPasswordChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPasswordChanged()
        End Sub

        #End Region
    End Class

    #End Region
    
End Namespace
