
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("c069db61-bc6d-4b21-b921-7c854160fd43")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ShipperCentralData", "FK_Order_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ShipperCentralData.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ShipperCentralData.Order), True)>
<Assembly: EdmRelationshipAttribute("ShipperCentralData", "FK_Order_OrderStatus", "OrderStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ShipperCentralData.OrderStatu), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ShipperCentralData.Order), True)>
<Assembly: EdmRelationshipAttribute("ShipperCentralData", "FK_OrderItem_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ShipperCentralData.Order), "OrderItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ShipperCentralData.OrderItem), True)>
<Assembly: EdmRelationshipAttribute("ShipperCentralData", "FK_OrderItem_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ShipperCentralData.Product), "OrderItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ShipperCentralData.OrderItem), True)>

#End Region
Namespace ShipperCentralData
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class ShipperCentralDataObjectContext
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new ShipperCentralDataObjectContext object using the connection string found in the 'ShipperCentralDataObjectContext' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=ShipperCentralDataObjectContext", "ShipperCentralDataObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new ShipperCentralDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "ShipperCentralDataObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new ShipperCentralDataObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "ShipperCentralDataObjectContext")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Customers() As ObjectSet(Of Customer)
            Get
                If (_Customers Is Nothing) Then
                    _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
                End If
                Return _Customers
            End Get
        End Property
    
        Private _Customers As ObjectSet(Of Customer)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Orders() As ObjectSet(Of Order)
            Get
                If (_Orders Is Nothing) Then
                    _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
                End If
                Return _Orders
            End Get
        End Property
    
        Private _Orders As ObjectSet(Of Order)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property OrderItems() As ObjectSet(Of OrderItem)
            Get
                If (_OrderItems Is Nothing) Then
                    _OrderItems = MyBase.CreateObjectSet(Of OrderItem)("OrderItems")
                End If
                Return _OrderItems
            End Get
        End Property
    
        Private _OrderItems As ObjectSet(Of OrderItem)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property OrderStatus() As ObjectSet(Of OrderStatu)
            Get
                If (_OrderStatus Is Nothing) Then
                    _OrderStatus = MyBase.CreateObjectSet(Of OrderStatu)("OrderStatus")
                End If
                Return _OrderStatus
            End Get
        End Property
    
        Private _OrderStatus As ObjectSet(Of OrderStatu)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Products() As ObjectSet(Of Product)
            Get
                If (_Products Is Nothing) Then
                    _Products = MyBase.CreateObjectSet(Of Product)("Products")
                End If
                Return _Products
            End Get
        End Property
    
        Private _Products As ObjectSet(Of Product)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCustomers(ByVal customer As Customer)
            MyBase.AddObject("Customers", customer)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrders(ByVal order As Order)
            MyBase.AddObject("Orders", order)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the OrderItems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrderItems(ByVal orderItem As OrderItem)
            MyBase.AddObject("OrderItems", orderItem)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the OrderStatus EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrderStatus(ByVal orderStatu As OrderStatu)
            MyBase.AddObject("OrderStatus", orderStatu)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToProducts(ByVal product As Product)
            MyBase.AddObject("Products", product)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ShipperCentralData", Name:="Customer")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Customer
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Customer object.
        ''' </summary>
        ''' <param name="customerID">Initial value of the CustomerID property.</param>
        Public Shared Function CreateCustomer(customerID As Global.System.Int32) As Customer
            Dim customer as Customer = New Customer
            customer.CustomerID = customerID
            Return customer
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CustomerID() As Global.System.Int32
            Get
                Return _CustomerID
            End Get
            Set
                If (_CustomerID <> Value) Then
                    OnCustomerIDChanging(value)
                    ReportPropertyChanging("CustomerID")
                    _CustomerID = value
                    ReportPropertyChanged("CustomerID")
                    OnCustomerIDChanged()
                End If
            End Set
        End Property
    
        Private _CustomerID As Global.System.Int32
        Private Partial Sub OnCustomerIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCustomerIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Firstname() As Global.System.String
            Get
                Return _Firstname
            End Get
            Set
                OnFirstnameChanging(value)
                ReportPropertyChanging("Firstname")
                _Firstname = value
                ReportPropertyChanged("Firstname")
                OnFirstnameChanged()
            End Set
        End Property
    
        Private _Firstname As Global.System.String
        Private Partial Sub OnFirstnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirstnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Surname() As Global.System.String
            Get
                Return _Surname
            End Get
            Set
                OnSurnameChanging(value)
                ReportPropertyChanging("Surname")
                _Surname = value
                ReportPropertyChanged("Surname")
                OnSurnameChanged()
            End Set
        End Property
    
        Private _Surname As Global.System.String
        Private Partial Sub OnSurnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSurnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Title() As Global.System.String
            Get
                Return _Title
            End Get
            Set
                OnTitleChanging(value)
                ReportPropertyChanging("Title")
                _Title = value
                ReportPropertyChanged("Title")
                OnTitleChanged()
            End Set
        End Property
    
        Private _Title As Global.System.String
        Private Partial Sub OnTitleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnTitleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address() As Global.System.String
            Get
                Return _Address
            End Get
            Set
                OnAddressChanging(value)
                ReportPropertyChanging("Address")
                _Address = value
                ReportPropertyChanged("Address")
                OnAddressChanged()
            End Set
        End Property
    
        Private _Address As Global.System.String
        Private Partial Sub OnAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property City() As Global.System.String
            Get
                Return _City
            End Get
            Set
                OnCityChanging(value)
                ReportPropertyChanging("City")
                _City = value
                ReportPropertyChanged("City")
                OnCityChanged()
            End Set
        End Property
    
        Private _City As Global.System.String
        Private Partial Sub OnCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Region() As Global.System.String
            Get
                Return _Region
            End Get
            Set
                OnRegionChanging(value)
                ReportPropertyChanging("Region")
                _Region = value
                ReportPropertyChanged("Region")
                OnRegionChanged()
            End Set
        End Property
    
        Private _Region As Global.System.String
        Private Partial Sub OnRegionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRegionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PostalCode() As Global.System.String
            Get
                Return _PostalCode
            End Get
            Set
                OnPostalCodeChanging(value)
                ReportPropertyChanging("PostalCode")
                _PostalCode = value
                ReportPropertyChanged("PostalCode")
                OnPostalCodeChanged()
            End Set
        End Property
    
        Private _PostalCode As Global.System.String
        Private Partial Sub OnPostalCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPostalCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Country() As Global.System.String
            Get
                Return _Country
            End Get
            Set
                OnCountryChanging(value)
                ReportPropertyChanging("Country")
                _Country = value
                ReportPropertyChanged("Country")
                OnCountryChanged()
            End Set
        End Property
    
        Private _Country As Global.System.String
        Private Partial Sub OnCountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Phone() As Global.System.String
            Get
                Return _Phone
            End Get
            Set
                OnPhoneChanging(value)
                ReportPropertyChanging("Phone")
                _Phone = value
                ReportPropertyChanged("Phone")
                OnPhoneChanged()
            End Set
        End Property
    
        Private _Phone As Global.System.String
        Private Partial Sub OnPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Mobile() As Global.System.String
            Get
                Return _Mobile
            End Get
            Set
                OnMobileChanging(value)
                ReportPropertyChanging("Mobile")
                _Mobile = value
                ReportPropertyChanged("Mobile")
                OnMobileChanged()
            End Set
        End Property
    
        Private _Mobile As Global.System.String
        Private Partial Sub OnMobileChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMobileChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Email() As Global.System.String
            Get
                Return _Email
            End Get
            Set
                OnEmailChanging(value)
                ReportPropertyChanging("Email")
                _Email = value
                ReportPropertyChanged("Email")
                OnEmailChanged()
            End Set
        End Property
    
        Private _Email As Global.System.String
        Private Partial Sub OnEmailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_Order_Customer", "Order")>
         Public Property Orders() As EntityCollection(Of Order)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("ShipperCentralData.FK_Order_Customer", "Order")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("ShipperCentralData.FK_Order_Customer", "Order", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ShipperCentralData", Name:="Order")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Order
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Order object.
        ''' </summary>
        ''' <param name="orderID">Initial value of the OrderID property.</param>
        ''' <param name="orderDate">Initial value of the OrderDate property.</param>
        ''' <param name="customerID">Initial value of the CustomerID property.</param>
        Public Shared Function CreateOrder(orderID As Global.System.Int32, orderDate As Global.System.DateTime, customerID As Global.System.Int32) As Order
            Dim order as Order = New Order
            order.OrderID = orderID
            order.OrderDate = orderDate
            order.CustomerID = customerID
            Return order
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderID() As Global.System.Int32
            Get
                Return _OrderID
            End Get
            Set
                If (_OrderID <> Value) Then
                    OnOrderIDChanging(value)
                    ReportPropertyChanging("OrderID")
                    _OrderID = value
                    ReportPropertyChanged("OrderID")
                    OnOrderIDChanged()
                End If
            End Set
        End Property
    
        Private _OrderID As Global.System.Int32
        Private Partial Sub OnOrderIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrderIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderDate() As Global.System.DateTime
            Get
                Return _OrderDate
            End Get
            Set
                OnOrderDateChanging(value)
                ReportPropertyChanging("OrderDate")
                _OrderDate = value
                ReportPropertyChanged("OrderDate")
                OnOrderDateChanged()
            End Set
        End Property
    
        Private _OrderDate As Global.System.DateTime
        Private Partial Sub OnOrderDateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnOrderDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShippingDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _ShippingDate
            End Get
            Set
                OnShippingDateChanging(value)
                ReportPropertyChanging("ShippingDate")
                _ShippingDate = value
                ReportPropertyChanged("ShippingDate")
                OnShippingDateChanged()
            End Set
        End Property
    
        Private _ShippingDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnShippingDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnShippingDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CustomerID() As Global.System.Int32
            Get
                Return _CustomerID
            End Get
            Set
                OnCustomerIDChanging(value)
                ReportPropertyChanging("CustomerID")
                _CustomerID = value
                ReportPropertyChanged("CustomerID")
                OnCustomerIDChanged()
            End Set
        End Property
    
        Private _CustomerID As Global.System.Int32
        Private Partial Sub OnCustomerIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCustomerIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property OrderStatusID() As Nullable(Of Global.System.Int32)
            Get
                Return _OrderStatusID
            End Get
            Set
                OnOrderStatusIDChanging(value)
                ReportPropertyChanging("OrderStatusID")
                _OrderStatusID = value
                ReportPropertyChanged("OrderStatusID")
                OnOrderStatusIDChanged()
            End Set
        End Property
    
        Private _OrderStatusID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnOrderStatusIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnOrderStatusIDChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_Order_Customer", "Customer")>
        Public Property Customer() As Customer
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ShipperCentralData.FK_Order_Customer", "Customer").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ShipperCentralData.FK_Order_Customer", "Customer").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CustomerReference() As EntityReference(Of Customer)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("ShipperCentralData.FK_Order_Customer", "Customer")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("ShipperCentralData.FK_Order_Customer", "Customer", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_Order_OrderStatus", "OrderStatus")>
        Public Property OrderStatu() As OrderStatu
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrderStatu)("ShipperCentralData.FK_Order_OrderStatus", "OrderStatus").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrderStatu)("ShipperCentralData.FK_Order_OrderStatus", "OrderStatus").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrderStatuReference() As EntityReference(Of OrderStatu)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OrderStatu)("ShipperCentralData.FK_Order_OrderStatus", "OrderStatus")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OrderStatu)("ShipperCentralData.FK_Order_OrderStatus", "OrderStatus", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_OrderItem_Order", "OrderItem")>
         Public Property OrderItems() As EntityCollection(Of OrderItem)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderItem)("ShipperCentralData.FK_OrderItem_Order", "OrderItem")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderItem)("ShipperCentralData.FK_OrderItem_Order", "OrderItem", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ShipperCentralData", Name:="OrderItem")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class OrderItem
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new OrderItem object.
        ''' </summary>
        ''' <param name="orderItemID">Initial value of the OrderItemID property.</param>
        Public Shared Function CreateOrderItem(orderItemID As Global.System.Int32) As OrderItem
            Dim orderItem as OrderItem = New OrderItem
            orderItem.OrderItemID = orderItemID
            Return orderItem
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderItemID() As Global.System.Int32
            Get
                Return _OrderItemID
            End Get
            Set
                If (_OrderItemID <> Value) Then
                    OnOrderItemIDChanging(value)
                    ReportPropertyChanging("OrderItemID")
                    _OrderItemID = value
                    ReportPropertyChanged("OrderItemID")
                    OnOrderItemIDChanged()
                End If
            End Set
        End Property
    
        Private _OrderItemID As Global.System.Int32
        Private Partial Sub OnOrderItemIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrderItemIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property OrderID() As Nullable(Of Global.System.Int32)
            Get
                Return _OrderID
            End Get
            Set
                OnOrderIDChanging(value)
                ReportPropertyChanging("OrderID")
                _OrderID = value
                ReportPropertyChanged("OrderID")
                OnOrderIDChanged()
            End Set
        End Property
    
        Private _OrderID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnOrderIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnOrderIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ProductID() As Nullable(Of Global.System.Int32)
            Get
                Return _ProductID
            End Get
            Set
                OnProductIDChanging(value)
                ReportPropertyChanging("ProductID")
                _ProductID = value
                ReportPropertyChanged("ProductID")
                OnProductIDChanged()
            End Set
        End Property
    
        Private _ProductID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnProductIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnProductIDChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_OrderItem_Order", "Order")>
        Public Property Order() As Order
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("ShipperCentralData.FK_OrderItem_Order", "Order").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("ShipperCentralData.FK_OrderItem_Order", "Order").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property OrderReference() As EntityReference(Of Order)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("ShipperCentralData.FK_OrderItem_Order", "Order")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Order)("ShipperCentralData.FK_OrderItem_Order", "Order", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_OrderItem_Product", "Product")>
        Public Property Product() As Product
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("ShipperCentralData.FK_OrderItem_Product", "Product").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("ShipperCentralData.FK_OrderItem_Product", "Product").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property ProductReference() As EntityReference(Of Product)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("ShipperCentralData.FK_OrderItem_Product", "Product")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("ShipperCentralData.FK_OrderItem_Product", "Product", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ShipperCentralData", Name:="OrderStatu")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class OrderStatu
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new OrderStatu object.
        ''' </summary>
        ''' <param name="orderStatusID">Initial value of the OrderStatusID property.</param>
        ''' <param name="statusDescription">Initial value of the StatusDescription property.</param>
        Public Shared Function CreateOrderStatu(orderStatusID As Global.System.Int32, statusDescription As Global.System.String) As OrderStatu
            Dim orderStatu as OrderStatu = New OrderStatu
            orderStatu.OrderStatusID = orderStatusID
            orderStatu.StatusDescription = statusDescription
            Return orderStatu
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderStatusID() As Global.System.Int32
            Get
                Return _OrderStatusID
            End Get
            Set
                If (_OrderStatusID <> Value) Then
                    OnOrderStatusIDChanging(value)
                    ReportPropertyChanging("OrderStatusID")
                    _OrderStatusID = value
                    ReportPropertyChanged("OrderStatusID")
                    OnOrderStatusIDChanged()
                End If
            End Set
        End Property
    
        Private _OrderStatusID As Global.System.Int32
        Private Partial Sub OnOrderStatusIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrderStatusIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property StatusDescription() As Global.System.String
            Get
                Return _StatusDescription
            End Get
            Set
                OnStatusDescriptionChanging(value)
                ReportPropertyChanging("StatusDescription")
                _StatusDescription = value
                ReportPropertyChanged("StatusDescription")
                OnStatusDescriptionChanged()
            End Set
        End Property
    
        Private _StatusDescription As Global.System.String
        Private Partial Sub OnStatusDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStatusDescriptionChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_Order_OrderStatus", "Order")>
         Public Property Orders() As EntityCollection(Of Order)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("ShipperCentralData.FK_Order_OrderStatus", "Order")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("ShipperCentralData.FK_Order_OrderStatus", "Order", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="ShipperCentralData", Name:="Product")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Product
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Product object.
        ''' </summary>
        ''' <param name="productID">Initial value of the ProductID property.</param>
        ''' <param name="specialOffer">Initial value of the SpecialOffer property.</param>
        Public Shared Function CreateProduct(productID As Global.System.Int32, specialOffer As Global.System.Boolean) As Product
            Dim product as Product = New Product
            product.ProductID = productID
            product.SpecialOffer = specialOffer
            Return product
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductID() As Global.System.Int32
            Get
                Return _ProductID
            End Get
            Set
                If (_ProductID <> Value) Then
                    OnProductIDChanging(value)
                    ReportPropertyChanging("ProductID")
                    _ProductID = value
                    ReportPropertyChanged("ProductID")
                    OnProductIDChanged()
                End If
            End Set
        End Property
    
        Private _ProductID As Global.System.Int32
        Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnProductIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ProductName() As Global.System.String
            Get
                Return _ProductName
            End Get
            Set
                OnProductNameChanging(value)
                ReportPropertyChanging("ProductName")
                _ProductName = value
                ReportPropertyChanged("ProductName")
                OnProductNameChanged()
            End Set
        End Property
    
        Private _ProductName As Global.System.String
        Private Partial Sub OnProductNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ProductImage() As Global.System.Byte()
            Get
                    Return StructuralObject.GetValidValue(_ProductImage)
            End Get
            Set
                OnProductImageChanging(value)
                ReportPropertyChanging("ProductImage")
                _ProductImage = value
                ReportPropertyChanged("ProductImage")
                OnProductImageChanged()
            End Set
        End Property
    
        Private _ProductImage As Global.System.Byte()
        Private Partial Sub OnProductImageChanging(value As Global.System.Byte())
        End Sub
    
        Private Partial Sub OnProductImageChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ProductCode() As Global.System.String
            Get
                Return _ProductCode
            End Get
            Set
                OnProductCodeChanging(value)
                ReportPropertyChanging("ProductCode")
                _ProductCode = value
                ReportPropertyChanged("ProductCode")
                OnProductCodeChanged()
            End Set
        End Property
    
        Private _ProductCode As Global.System.String
        Private Partial Sub OnProductCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SpecialOffer() As Global.System.Boolean
            Get
                Return _SpecialOffer
            End Get
            Set
                OnSpecialOfferChanging(value)
                ReportPropertyChanging("SpecialOffer")
                _SpecialOffer = value
                ReportPropertyChanged("SpecialOffer")
                OnSpecialOfferChanged()
            End Set
        End Property
    
        Private _SpecialOffer As Global.System.Boolean
        Private Partial Sub OnSpecialOfferChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnSpecialOfferChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property RRP() As Nullable(Of Global.System.Decimal)
            Get
                Return _RRP
            End Get
            Set
                OnRRPChanging(value)
                ReportPropertyChanging("RRP")
                _RRP = value
                ReportPropertyChanged("RRP")
                OnRRPChanged()
            End Set
        End Property
    
        Private _RRP As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnRRPChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnRRPChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property SupplierCode() As Global.System.String
            Get
                Return _SupplierCode
            End Get
            Set
                OnSupplierCodeChanging(value)
                ReportPropertyChanging("SupplierCode")
                _SupplierCode = value
                ReportPropertyChanged("SupplierCode")
                OnSupplierCodeChanged()
            End Set
        End Property
    
        Private _SupplierCode As Global.System.String
        Private Partial Sub OnSupplierCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSupplierCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Comment() As Global.System.String
            Get
                Return _Comment
            End Get
            Set
                OnCommentChanging(value)
                ReportPropertyChanging("Comment")
                _Comment = value
                ReportPropertyChanged("Comment")
                OnCommentChanged()
            End Set
        End Property
    
        Private _Comment As Global.System.String
        Private Partial Sub OnCommentChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCommentChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Weight() As Nullable(Of Global.System.Decimal)
            Get
                Return _Weight
            End Get
            Set
                OnWeightChanging(value)
                ReportPropertyChanging("Weight")
                _Weight = value
                ReportPropertyChanged("Weight")
                OnWeightChanged()
            End Set
        End Property
    
        Private _Weight As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnWeightChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnWeightChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("ShipperCentralData", "FK_OrderItem_Product", "OrderItem")>
         Public Property OrderItems() As EntityCollection(Of OrderItem)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderItem)("ShipperCentralData.FK_OrderItem_Product", "OrderItem")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderItem)("ShipperCentralData.FK_OrderItem_Product", "OrderItem", value)
                End If
            End Set
        End Property

        #End Region
    End Class

    #End Region
    
End Namespace
